# Generated by Django 4.2.7 on 2026-04-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheme_multilingual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
