# Generated by Django 4.2.7 on 2026-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('market_date', models.DateField(db_index=True)),
                ('market_location', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(default='Auto', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mu_price_history',
                'ordering': ['-market_date', 'commodity_name'],
                'indexes': [models.Index(fields=['commodity_name', '-market_date'], name='mu_price_hi_commodi_40a602_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(db_index=True, max_length=200)),
                ('analysis_date', models.DateField(auto_now_add=True, db_index=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price_30d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price_30d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_30d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('trend_percentage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('momentum_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analysis_type', models.CharField(choices=[('trend', 'Trend Analysis'), ('volatility', 'Volatility'), ('momentum', 'Momentum'), ('seasonal', 'Seasonal')], default='trend', max_length=20)),
                ('insights', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], default='hold', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mu_market_price_analysis',
                'ordering': ['-analysis_date', 'commodity_name'],
                'unique_together': {('commodity_name', 'analysis_date')},
            },
        ),
    ]
